export const musics = [
    {
        title: 'music1',
        cover: 'https://image.bugsm.co.kr/album/images/500/1512/151262.jpg',
        singer: 'Nell',
        singerCover:'https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/2mfB/image/R8GLZlp58OLS1ozlZS5wvyqA5_Y.jpg',
        genre: 'genre1',
        album: 'album1',
        musicFile: './music/music1.mp3',
        heart: 10,
    },
    {
        title: 'music2',
        cover: 'https://image.bugsm.co.kr/album/images/500/1512/151262.jpg',
        singer: 'Nell',
        singerCover:'https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/2mfB/image/R8GLZlp58OLS1ozlZS5wvyqA5_Y.jpg',
        genre: 'genre2',
        album: 'album1',
        musicFile: './music/music1.mp3',
        heart: 10,
    },
    {
        title: 'music3',
        cover: 'https://image.aladin.co.kr/product/3718/88/cover500/4775054147_1.jpg',
        singer: 'Nell',
        singerCover:'https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/2mfB/image/R8GLZlp58OLS1ozlZS5wvyqA5_Y.jpg',
        genre: 'genre3',
        album: 'album1',
        musicFile: './music/music1.mp3',
        heart: 10,
    },
    {
        title: 'music4',
        cover: 'https://i.ytimg.com/vi/WNjZbszU7eY/hqdefault.jpg',
        singer: 'Nell',
        singerCover:'https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/2mfB/image/R8GLZlp58OLS1ozlZS5wvyqA5_Y.jpg',
        genre: 'genre4',
        album: 'album1',
        musicFile: './music/music1.mp3',
        heart: 10,
    },
    {
        title: 'music5',
        cover: 'https://i.ytimg.com/vi/WNjZbszU7eY/hqdefault.jpg',
        singer: 'Nell',
        singerCover:'https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/2mfB/image/R8GLZlp58OLS1ozlZS5wvyqA5_Y.jpg',
        genre: 'genre5',
        album: 'album1',
        musicFile: './music/music1.mp3',
        heart: 10,
    }
]
