export const musics = [
    {
        title: '기억을 걷는 시간',
        cover: 'https://image.bugsm.co.kr/album/images/500/1512/151262.jpg',
        singer: 'Nell',
        singerCover:'https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/2mfB/image/R8GLZlp58OLS1ozlZS5wvyqA5_Y.jpg',
        genre: 'Indie, Rock',
        album: 'Separation Anxiety',
        musicFile: './music/기억을_걷는_시간.mp3',
        heart: 10,
    },
    {
        title: '멀어지다',
        cover: 'https://image.bugsm.co.kr/album/images/500/1512/151262.jpg',
        singer: 'Nell',
        singerCover:'https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/2mfB/image/R8GLZlp58OLS1ozlZS5wvyqA5_Y.jpg',
        genre: 'Indie, Rock',
        album: 'Separation Anxiety',
        musicFile: './music/멀어지다.mp3',
        heart: 10,
    },
    {
        title: '지구가 태양을 네번',
        cover: 'https://image.aladin.co.kr/product/3718/88/cover500/4775054147_1.jpg',
        singer: 'Nell',
        singerCover:'https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/2mfB/image/R8GLZlp58OLS1ozlZS5wvyqA5_Y.jpg',
        genre: 'Indie, Rock',
        album: 'Newton\'s Apple',
        musicFile: './music/지구가_태양을_네번.mp3',
        heart: 10,
    },
    {
        title: '타인의 기억',
        cover: 'https://image.aladin.co.kr/product/3718/88/cover500/4775054147_1.jpg',
        singer: 'Nell',
        singerCover:'https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/2mfB/image/R8GLZlp58OLS1ozlZS5wvyqA5_Y.jpg',
        genre: 'Indie, Rock',
        album: 'Newton\'s Apple',
        musicFile: './music/타인의_기억.mp3',
        heart: 10,
    },
    {
        title: 'Stay',
        cover: 'https://upload.wikimedia.org/wikipedia/ko/thumb/8/8a/%EB%84%AC_-_Let_It_Rain.jpg/220px-%EB%84%AC_-_Let_It_Rain.jpg',
        singer: 'Nell',
        singerCover:'https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/2mfB/image/R8GLZlp58OLS1ozlZS5wvyqA5_Y.jpg',
        genre: 'Indie, Rock',
        album: 'Let it Rain',
        musicFile: './music/Stay.mp3',
        heart: 10,
    }
]
